# --- !Ups

CREATE TYPE share_request_type  AS ENUM ('retrieve', 'delete');
CREATE TYPE share_request_state AS ENUM ('pending', 'approved', 'denied');

-- One row per (secret, recipient) pair.
-- secret_id is a UUID generated by the sender at split time; the same secret_id appears
-- across all n shares of a given split.
-- sender_key and recipient_key are Ed25519 public keys (32 bytes).
-- The server uses them solely for routing and access control — it never decrypts ciphertext.
-- ciphertext is the share bytes encrypted to the recipient's X25519 public key (exchanged
-- out-of-band); the server never sees X25519 keys.
CREATE TABLE shares (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    secret_id      UUID        NOT NULL,
    label          TEXT        NOT NULL,
    sender_key     BYTEA       NOT NULL,
    recipient_key  BYTEA       NOT NULL,
    ciphertext     BYTEA       NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (secret_id, recipient_key)
);

-- Tracks pending consent requests (retrieve or delete) from the sender to the recipient.
-- The requester is always the sender (shares.sender_key); the server enforces this
-- by verifying the authenticated key against shares.sender_key when a request is opened.
-- The partial unique index prevents duplicate pending requests of the same type on the
-- same share; a new request can only be opened once the previous one is resolved.
CREATE TABLE share_requests (
    id           UUID                PRIMARY KEY DEFAULT gen_random_uuid(),
    share_id     UUID                NOT NULL REFERENCES shares(id) ON DELETE CASCADE,
    request_type share_request_type  NOT NULL,
    state        share_request_state NOT NULL DEFAULT 'pending',
    requested_at TIMESTAMPTZ         NOT NULL DEFAULT now(),
    responded_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_share_requests_one_pending_per_type
    ON share_requests (share_id, request_type)
    WHERE state = 'pending';

-- Indexes for common query paths
CREATE INDEX ON shares (recipient_key);
CREATE INDEX ON shares (sender_key);
CREATE INDEX ON shares (secret_id);
CREATE INDEX ON share_requests (share_id);

# --- !Downs

DROP TABLE share_requests;
DROP TABLE shares;

DROP TYPE share_request_state;
DROP TYPE share_request_type;
