# DB configuration

db.default.driver = org.postgresql.Driver
db.default.url = ${?POSTGRESQL_URI}

# https://www.playframework.com/documentation/latest/AccessingAnSQLDatabase#Using-a-CustomExecutionContext
database.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = 10 # ${db.default.hikaricp.maximumPoolSize}
  }
}


# i18n/l10n configuration

play.i18n.langs = ["en", "de"]
