# DB configuration

db.default.driver = org.postgresql.Driver
db.default.url = ${?POSTGRESQL_URI}

# https://www.playframework.com/documentation/latest/AccessingAnSQLDatabase#Using-a-CustomExecutionContext
database.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = 10 # ${db.default.hikaricp.maximumPoolSize}
  }
}


# i18n/l10n configuration

play.i18n.langs = ["en", "de"]
play.filters.enabled += filters.LocaleFilter


# security configuration

play.filters.csp.directives.default-src = "'none'"
play.filters.csp.directives.connect-src = "'self'"
play.filters.csp.directives.font-src = "'self'"
play.filters.csp.directives.frame-ancestors = "'none'"
play.filters.csp.directives.frame-src = "'self'"
play.filters.csp.directives.img-src = "'self'"
play.filters.csp.directives.manifest-src = "'self'"
play.filters.csp.directives.script-src = "'self'"
play.filters.csp.directives.style-src = "'self'"

play.filters.hosts.allowed = [".deposplit.com", ${?PAAS_DOMAIN}]

# security-ish
play.filters.enabled += filters.ApiHostPathFilter
