include "application"

db.default.driver = org.h2.Driver
db.default.url = "jdbc:h2:./target/deposplit-dev;MODE=PostgreSQL;DATABASE_TO_UPPER=FALSE"
# db.default.driver = org.postgresql.Driver
# db.default.url = "postgresql://PSuser:PSpassword@localhost:5432/PSuser"

# iOS Simulator uses localhost (or 127.0.0.1) and so does the browser
# Android Emulator uses 10.0.2.2 (https://developer.android.com/studio/run/emulator-networking-address)
play.filters.hosts.allowed = ["localhost:9000", "127.0.0.1:9000", "10.0.2.2:9000"]
