include "localhost"

db.default.url = "jdbc:h2:mem:play;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE"
play.evolutions.db.default.autoApply = true

# Play's FakeRequest uses "localhost" (no port) as the default Host header
play.filters.hosts.allowed = ["localhost"]
